- name: Install packages core
  become: true
  apt:
    name:
      [
        "lsof",
        "curl",
        "dconf-editor",
        "nvidia-settings",
        "pavucontrol",
        "unzip",
        "solaar",
        "gnome-tweaks",
        "gnome-shell-extensions",
      ]
  tags:
    - install
    - core

- name: Dependencies for build neovim
  become: true
  apt:
    name: ["cmake", "lua5.1", "gettext"]
  tags:
    - install
    - core
    - neovim

- name: Install snaps
  become: true
  community.general.snap:
    name:
      - code
      - obsidian
      - postman
      - vlc
    classic: true
  tags:
    - install
    - snaps

- name: Clone dotfiles
  git:
    repo: "git@github.com:Jehezkel/dotfiles.git"
    dest: "~/repos/dotfiles"
    force: true
  tags:
    - install
    - dotfiles

- name: Copy dotfiles
  copy:
    src: ~/repos/dotfiles/
    dest: ~/.config/
  tags:
    - dotfiles
    - install
