- name: Create global directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/.npm-global"
    state: directory
    mode: '0755'
  tags: &tags_for_node [ 'install', 'node' ]

- name: Install node and npm
  apt:
    name:
      - npm
      - nodejs
  tags: *tags_for_node

- name: Set npm global
  shell: npm config set prefix '~/.local/.npm-global'npm
  tags: *tags_for_node
